INSERT INTO movies (movie_name)
VALUES

("24 x 36: A Movie About Movie Posters (2016) "),
("The 10th Victim (1965)"),
("100 Feet (2008)"),
("12 Years a Slave (2013) "),
("13 Conversations About One Thing (2002)"),
("1408 (2007)"),
("1776 (1972)"),
("1917 (2019)"),
("1990: The Bronx Warriors (1982)"),
("The 2000 Year Old Man (1975)"),
("20,000 Leagues Under the Sea (1954)"),
("2001: A Space Odyssey (1968)"),
("2010: The Year We Make Contact (1984)"),
("2019: After the Fall of New York (1983)"),
("2069: A Sex Odyssey (1974)"),
("20th Century Fox: The 1st 50 Years (1997)"),
("20th Century Fox: The Blockbuster Years (2000)"),
("25th Hour (2002)"),
("3 Dead Girls (2007)"),
("30 Days of Night (2007)"),
("31 (2016) "),
("The 39 Steps (1935)"),
("4 Dollars of Revenge (1968)");

INSERT INTO reviews (movie_id, review)
VALUES
(1,"This documentary from Ryan White rewinds, to powerful effect, on Pamela Anderson’s life and fame."),
(2,"The Italian director Mario Martone creates an expressive, economic depiction of crime and longing in this drama about a man coming home to Naples."),
(3,"A wealthy writer succumbs to the lure of consequence-free violence in this artfully potent blend of horror and science fiction."),
(4,"Jonah Hill and Eddie Murphy are among the stars in this prickly-charming generational Netflix comedy, the feature directing debut of Kenya Barris."),
(5,"In this thriller, a French diplomat takes to the road after being falsely imprisoned by Russian authorities."),
(6,"This film, featuring a captivating performance from David Strathairn as the Polish resistance fighter Jan Karski, is a straightforward adaptation of the play of the same name."),
(7,"Friendship and tragedy go hand in hand in Lukas Dhont’s delicate, Oscar-nominated drama."),
(8,"Teenagers from the Church of Jesus Christ of Latter-day Saints travel to Finland for missionary service in this documentary that offers limited insight."),
(9,"The election of a grand imam is the backdrop for this tense drama of innocence and corruption set at an esteemed Islamic university."),
(10,"Looking at the seasoned cast — Diane Keaton, Richard Gere, Susan Sarandon and William H. Macy — you might think you want to see this movie. Hold that thought."),
(11,"Jean-Christophe Klotz’s documentary retraces the steps of two men tasked with gathering evidence for the Nuremberg trials."),
(12,"A destination wedding becomes a high-stakes hostage situation in this action-heavy film."),
(13,"Couples try to navigate relationships in lockdown in this pandemic satire."),
(14,"This nebulous French thriller tracks the unraveling of a Jewish family that accidentally sells their storage cellar to an antisemitic conspiracy theorist."),
(15,"Part nature film, part biographical portrait, this experimental documentary takes its cues from its setting, an island off mainland Nova Scotia."),
(16,"The audacious sequel to Frant Gwo’s 2019 sci-fi blockbuster follows survivors working to avert planetary disaster, but it loses much of the glee of its predecessor."),
(17,"This observational documentary about an aging farming couple on the Icelandic coast unfolds like an elegy to a life lived off the land."),
(18,"In this intelligent melodrama by the director Aleem Khan, a British woman discovers her husband has been leading a double life."),
(19,"In Matt Carter’s gay rugby film, sports and romance smash together like two players from opposing teams."),
(20,"In this animated fantasy, a former deity must confront his traumatic past if he hopes to find absolution and save the world."),
(21,"Julianne Moore plays a parent to a son (Finn Wolfhard) with whom she fails to see eye-to-eye in this comedy directed by Jesse Eisenberg."),
(22,"Anna Kendrick stars in a drama about a woman in an abusive relationship who finds refuge with two girlfriends during a getaway."),
(23,"This thriller, about a teenage girl whose mother disappears, plays out on a computer screen."),
(1,"A series of sexual and social situations unspool in this portrait of Israeli youth culture."),
(2,"Laemmle theaters have fed generations of Los Angeles cinephiles. This documentary looks at their past and present."),
(3,"After a decade on the shelf, this action comedy is streaming for the first time. But while the action is dated, the comedy is antique."),
(4,"Li Xiaofeng’s film turns a crime soap opera into an allegory about China’s head-spinning modernization."),
(5,"Directed by Calmatic, “House Party” reboots the 1990 Kid ’n Play cult comedy with the help of LeBron James."),
(6,"In this Netflix family movie, based on a true story, a yellow Lab disappears on the Appalachian Trail, and Rob Lowe is tasked with finding him."),
(7,"A real-life case of infanticide is the basis of Alice Diop’s rigorous and wrenching courtroom drama."),
(8,"Two children are trapped in a shape-shifting home in this spookily impenetrable horror experiment."),
(9,"Gillian Jacobs’s blank slate protagonist floats through a series of encounters in this feature-length movie made up of short films."),
(10,"In this brutal Icelandic drama, four teenagers — both bullies and the bullied — struggle and rage against a world that rages back."),
(11,"A sous chef is forced to take a job at a hostel for undocumented minors in this feel-good drama with a white-savior problem."),
(12,"In this thriller, Gerard Butler and Mike Colter have to avoid a hostage situation and deliver a plane full of passengers to safety."),
(13,"In this Brooklyn-set horror film, an evil spirit causes torment at a Jewish funeral home."),
(14,"A new documentary from Gédéon and Jules Naudet recounts the day of the U.S. Capitol attack."),
(15,"This film from Gabriel Martins follows the dreams of a Black Brazilian family living on the outskirts of Belo Horizonte."),
(16,"A state-of-the-art robot doll becomes a girl’s best friend, and dangerously more, in this over-the-top horror film."),
(17,"In this action film set in Bangkok, a special forces guy goes in to rescue his wife and daughter."),
(18,"In this sleazy slasher by the writer and director John Swab, a group of sex workers adopts a former member of a religious cult."),
(19,"Nicolas Cage phones it in as a deadly, taciturn gunslinger in this middling western."),
(20,"In this naturalistic drama from Spain, a family confronts the impending loss of its generations-old farm."),
(21,"The writer Mark Manson is an onscreen guide in this visualization of his self-help book."),
(22,"This affectionate documentary about the writer Robert Caro and the editor Robert Gottlieb sets out to shed light on their 50 years of collaboration."),
(23,"This documentary follows a couple’s efforts to reintroduce an ocelot, headed to a zoo or worse, into its home in the Peruvian Amazon."),
(1,"This festival’s 22nd edition covers themes of crisis, both personal and planetary, with short works from the likes of Gil Alkabetz and Frédéric Back."),
(2,"Going against nice-guy type (at first), the star plays a misanthrope who’s pulled into caring for a neighboring family in need."),
(3,"Stakeholders including Patti LuPone and Lynn Nottage share their real-time reactions to New York theater’s shutdown and reopening in Amy Rice’s documentary."),
(4,"This musical adaptation of Roald Dahl’s novel is a jolt of sour candy guaranteed to make you grin."),
(5,"Filmed in South Korea, the new movie from Hirokazu Kore-eda turns a potentially grim tale into a poignant road picture."),
(6,"A transfixing Vicky Krieps plays the Empress of Austria who, at 40, begins to chafe against her predictably cosseted life."),
(7,"Sarah Polley adapts Miriam Toews’s novel into a timely political parable with a stellar ensemble cast."),
(8,"The latest feature from Jafar Panahi, who is currently imprisoned in Iran, explores the subversive power and the ethical limitations of filmmaking."),
(9,"Damien Chazelle directs Brad Pitt, Margot Robbie and Diego Calva in a 1920s story about Hollywood’s good and sometimes very bad old days."),
(10,"Bill Nighy stars as a buttoned-up bureaucrat transformed by a grim diagnosis in this drama by the novelist Kazuo Ishiguro, adapted from an Akira Kurosawa movie."),
(11,"This film from Kasi Lemmons is a jukebox retelling of Whitney Houston’s parabola from sweatshirts to sequins.");
